CREATE DATABASE CRUDPT;
GO
USE CRUDPT;
GO
CREATE TABLE Roles(
Nombre VARCHAR(30) NOT NULL,
Descripcion VARCHAR(100)NOT NULL,
Estado TINYINT NOT NULL,
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL
);
GO
CREATE TABLE Usuarios(
Nombre VARCHAR(30)NOT NULL,
CorreoElectronico VARCHAR(30)NOT NULL,
Contraseña VARCHAR(30)NOT NULL,
Estado TINYINT NOT NULL,
IdRol INT NOT NULL,
Id INT PRIMARY KEY IDENTITY(1,1)NOT NULL,
FOREIGN KEY (IdRol)REFERENCES Usuarios(Id)
);
GO

